### ISSUE TITLE
Spelling of "present"

### ISSUE THREAD

**Issue by variableresistor** [JustinGrote/PoshRegistry#3]
This is a bit of nit-picking on my part, but the word "present" is misspelled in the following verbose statements in Get-RegDWord.ps1:
Write-Verbose "Parameter [ComputerName] is not presnet, setting its value to local computer name: [$c]."
Write-Verbose "Parameter [AsHex] is presnet, return value as HEX."
Write-Verbose "Parameter [AsHex] is not presnet, return value as INT."
Write-Verbose "Parameter [Ping] is presnet, initiating Ping test"

I retrieved this module to view using PowerShell Get:
Save-Module -Name PoshRegistry -Path $env:USERPROFILE

**Comment by JustinGrote** [comment]
Thanks, I'm working on my CI pipeline so I don't know when this will get back out to PSGallery, but I'll update when I do.
